# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  geometry-msgs,
  perseus-interfaces,
  rclpy,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-crater-exit";
  version = "0.1.0";

  src = ./../src/crater_exit;

  buildType = "ament_python";
  propagatedBuildInputs = [
    geometry-msgs
    perseus-interfaces
    rclpy
    sensor-msgs
    std-msgs
  ];

  meta = {
    description = "Crater exit behavior node - detects when the rover is stuck in a crater and drives forward until IMU pitch indicates the rim has been crested";
    license = with lib.licenses; [ mit ];
  };
}
