# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  geometry-msgs,
  nav-msgs,
  nav2-msgs,
  rclcpp,
  rclcpp-action,
  tf2,
  tf2-geometry-msgs,
  tf2-ros,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-explorer";
  version = "0.0.0";

  src = ./../src/perseus_lite_explorer;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    geometry-msgs
    nav-msgs
    nav2-msgs
    rclcpp
    rclcpp-action
    tf2
    tf2-geometry-msgs
    tf2-ros
    visualization-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Frontier-based autonomous exploration for Perseus Lite";
    license = with lib.licenses; [ mit ];
  };
}
