twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      joystick:
        topic: /joy_vel
        timeout: 0.5
        priority: 10 # Higher priority - joystick overrides nav
      navigation:
        topic: /nav_vel # From collision_monitor
        timeout: 0.5
        priority: 5 # Lower priority - nav runs when joystick inactive
